version: '3'

volumes:
  pg_data:
  static:
  media:
  frontend_static:

services:
  db:
    restart: on-failure:3
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 20
  backend:
    image: ezhik415/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    image: ezhik415/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - frontend_static:/frontend_static
  gateway:
    image: ezhik415/foodgram_gateway
    env_file: .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_static:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/staticfiles
      - media:/media
    ports:
      - 8080:80
    depends_on:
      - backend
      - frontend
