EMAIL_FIELD_LENGTH = 254
USERNAME_LENGTH = 150
USERNAME_VALID_PATTERN = r'[\w.@+-]'
URL_PROFILE_PREF = 'me'
URL_SET_PASSWORD = 'set_password'
TAG_COLOR_VALID_PATTERN = r'^#[0-9a-fA-F]{6}$'
FIRST_NAME_LENGTH = 150
LAST_NAME_LENGTH = 150
PASSWORD_LENGTH = 150
NAME_MAX_LENGTH = 60
SLUG_MAX_LENGTH = 50
TAG_COLOR_MAX_LENGTH = 7
DESCRIPTION_MAX_LENGTH = 1024
COOKING_TIME_MAX_VALUE = 1440
COOKING_TIME_MIN_VALUE = 1
TEXT_LIMIT = 20

