# Generated by Django 3.2.16 on 2024-04-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20240426_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'default_related_name': 'ingredientsrecipes', 'verbose_name': 'ИнгредиентРецепт', 'verbose_name_plural': 'ИнгредиентыРецепты'},
        ),
    ]
