# Generated by Django 3.2.16 on 2024-04-29 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriterecipe',
            old_name='favorite_recipe',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='shopping_cart',
            new_name='recipe',
        ),
    ]
