# Generated by Django 3.2.16 on 2024-05-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20240501_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.TextField(max_length=1024, verbose_name='Описание'),
        ),
    ]
